export const GTFlavors = [
    {
        "brand": "GT's Synergy",
        "name": "Passionberry Bliss",
        "profile": "fruit",
        "comments": "Very delicious. etc...",
        "repurchase": "Yes",
    },
    {
        "brand": "GT's Synergy",
        "name": "Peach Paradise",
        "profile": "fruit",
        "comments": "very delicious...",
        "repurchase": "Yes",
    },
    {
        "brand": "GT's Synergy",
        "name": "Gingerberry",
        "profile": "fruit, spice",
        "comments": "pretty good...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Guava Goddess",
        "profile": "fruit",
        "comments": "pretty good...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Golden Pineapple",
        "profile": "fruit",
        "comments": "very delicious...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Lemon Berry",
        "profile": "fruit, citrus",
        "comments": "very delicious....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Watermelon Wonder",
        "profile": "fruit",
        "comments": "very good",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Sacred Life",
        "profile": "fruit, spice, other",
        "comments": "very good (describe other)",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Tangerine Dream",
        "profile": "citrus",
        "comments": "very good",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Mystic Mango",
        "profile": "fruit",
        "comments": "very good....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Living In Gratitude",
        "profile": "spice, fruit",
        "comments": "very good, one of my favorites",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Carrot Turmeric",
        "profile": "spice",
        "comments": "very good....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Hibiscus Ginger",
        "profile": "floral, spice",
        "comments": "not very good....",
        "repurchase": "No",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Raspberry Chia",
        "profile": "fruit, chia seeds",
        "comments": "very good",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Strawberry Serenity",
        "profile": "fruit",
        "comments": "not very good",
        "repurchase": "No",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Strawberry Lemonade",
        "profile": "fruit, citrus",
        "comments": "better than the regular strawberry....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Pink Lady Apple",
        "profile": "fruit",
        "comments": "pretty good...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Cosmic Cranberry",
        "profile": "fruit",
        "comments": "very good...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Multi-Green",
        "profile": "other",
        "comments": "not bad.....",
        "repurchase": "No",
    },
    {
        "img": "",
        "brand": "GT's Synergy",
        "name": "Gingerade",
        "profile": "spice",
        "comments": "not bad...",
        "repurchase": "Yes",
    },
]



// {
//     "img": "",
//     "brand": "",
//     "name": "",
//     "profile": "",
//     "comments": "",
//     "repurchase": "",
// },