export const HealthFlavors = [
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Pineapple Creamsicle",
        "profile": "fruit, cream",
        "comments": "very good...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Holiday Cheers",
        "profile": "spice",
        "comments": "pretty good...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Pink Lady Apple",
        "profile": "fruit",
        "comments": "pretty good....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Pomegranate",
        "profile": "fruit",
        "comments": "very good...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Bubbly Rose",
        "profile": "floral",
        "comments": "not great...",
        "repurchase": "No",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Tropical Punch",
        "profile": "fruit",
        "comments": "pretty good....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Passionfruit Tangerine",
        "profile": "fruit, citrus",
        "comments": "pretty good....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Ginger Lemon",
        "profile": "spice, citrus",
        "comments": "very medicinal, good....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Blood-Orange Carrot Ginger",
        "profile": "citrus, spice",
        "comments": "pretty good",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Watermelon",
        "profile": "fruit",
        "comments": "pretty good...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "Health-Ade",
        "name": "Strawberry Glow",
        "profile": "fruit",
        "comments": "not bad...",
        "repurchase": "No",
    },
]