export const KevitaFlavors = [
    {
        "img": "",
        "brand": "KeVita Master Brew",
        "name": "Tart Cherry",
        "profile": "fruit, spice",
        "comments": "cherry and ginger do not go together....",
        "repurchase": "No",
    },
    {
        "img": "",
        "brand": "KeVita Master Brew",
        "name": "Pineapple Peach",
        "profile": "fruit, spice",
        "comments": "pretty good....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "KeVita Master Brew",
        "name": "Raspberry Lemonade",
        "profile": "fruit, citrus, spice",
        "comments": "ehhhhhhh...",
        "repurchase": "No",
    },
    {
        "img": "",
        "brand": "KeVita Sparkling Probiotic",
        "name": "Lemon Ginger",
        "profile": "citrus, spice",
        "comments": "not bad...",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "KeVita Sparkling Probiotic",
        "name": "Mango Coconut",
        "profile": "fruit, other",
        "comments": "describe other",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "KeVita Sparkling Probiotic",
        "name": "pomegranate",
        "profile": "fruit",
        "comments": "very good.....",
        "repurchase": "Yes",
    },
    {
        "img": "",
        "brand": "KeVita Sparkling Probiotic",
        "name": "Strawberry Acai Coconut",
        "profile": "fruit, other",
        "comments": "describe other",
        "repurchase": "Yes",
    },
]